### ISSUE TITLE
Can you run Daniel Neil's code?

### ISSUE THREAD

**Issue by zxzhijia** [duguyue100/transpike#1]
Hi duguyue100,

I'm trying to  run Daniel's training.py code. But it seems his code reports error on latest keras version. I have several questions about his code. Do you mind to answer from your point of view?

1. why does he build Conv2DNoBias, DenseNoBias other than direct set used_bias=False in Keras?
2. Why does he build AveragePooling2D other than use the Keras's original AveragePooling2D?
3. I tried to use Keras to train a network without bias and mapping it to his testing code. The accuracy is really bad. I haven't figured out why.

Thank you in advance.

**Comment by duguyue100** [comment]
Hi, @zxzhijia, Ok, so I wrote this project long time ago, and actually in the end we developed the entire toolkit for converting analog network to spiking counterpart in Python with Keras. But for sure this project wouldn't work, or it's only working in limited usage. Sorry I couldn't share the code with you since right now it's still a private project.

I think while Danny wrote his project with Keras, Keras wasn't even reached to 1.0 yet, now Keras version jumped to 2.x. So there are a lot of API changes.

I think the reason he built the entire system himself because he needs some custom modification through time. It was long time ago, so I'm not really sure about it.

Maybe you would want to follow our recent work on this: https://arxiv.org/abs/1612.04052
This may give you some broader idea of how network conversion works.

**Comment by zxzhijia** [comment]
Hi, @duguyue100 , thanks for your quick reply. Yes, that's a great paper. I've read that before. I'm trying to find an open source code written in python that do the conversion. But it seems there is no one that works well in current version of keras or theano.

**Comment by duguyue100** [comment]
Yeah, I know. somehow people don't want to reveal their code (our code is kept private because some grant reasons)

**Comment by zxzhijia** [comment]
I see. thank you anyway. : )
